### ISSUE TITLE
 Publish this Action to Marketplace 

### ISSUE THREAD

**Issue by leestott** [microsoft/pybryt-action#1]
Publish this Action to Marketplace Make your Action discoverable on GitHub Marketplace and in GitHub search.
 @chrispyles

**Comment by chrispyles** [comment]
@leestott Yes I'm aware this still needs to be published. I've been holding off until we do 1 or 2 more rounds of ambassadors assignments just to make sure there aren't any bugs or changes to be made before an official release.

**Comment by leestott** [comment]
V1. of PyBryt actions published https://github.com/marketplace/actions/assess-with-pybryt
